### ISSUE TITLE
Cape client base_api not running

### ISSUE THREAD

**Issue by samredway** [bloomsburyai/cape-client#1]
If you look at line 38 in client.py

`def __init__(self, api_base='https://responder.thecape.ai/api', admin_token=None):`

It looks like this url/endpoint is no longer alive. Should a `base_api` now be a required positional argument?

Presumably the user needs to run their own backend somewhere (eg locally in docker)?

I put in a PR for this

**Comment by Elleo** [comment]
That's a good point, thanks for spotting and it and thanks for the PR
